pyuic5 -x DocAccounting/views/ui/MainWindow.ui -o DocAccounting/views/ui/ui_main_window.py
pyuic5 -x DocAccounting/views/ui/AboutDialog.ui -o DocAccounting/views/ui/ui_about_dialog.py
pyuic5 -x DocAccounting/views/ui/EmployeesDialog.ui -o DocAccounting/views/ui/ui_employees_dialog.py
pyuic5 -x DocAccounting/views/ui/StatusDocsDialog.ui -o DocAccounting/views/ui/ui_statusdocs_dialog.py
pyuic5 -x DocAccounting/views/ui/PositionsDialog.ui -o DocAccounting/views/ui/ui_positions_dialog.py
pyuic5 -x DocAccounting/views/ui/DevelopersDialog.ui -o DocAccounting/views/ui/ui_developers_dialog.py
pyuic5 -x DocAccounting/views/ui/SourcesDialog.ui -o DocAccounting/views/ui/ui_sources_dialog.py
pyuic5 -x DocAccounting/views/ui/CategoryDocsDialog.ui -o DocAccounting/views/ui/ui_category_docs_dialog.py
pyuic5 -x DocAccounting/views/ui/DocsAccDialog.ui -o DocAccounting/views/ui/ui_docs_acc_dialog.py
pyuic5 -x DocAccounting/views/ui/DocsDownloadDialog.ui -o DocAccounting/views/ui/ui_docs_download_dialog.py
pyuic5 -x DocAccounting/views/ui/DocsUploadDialog.ui -o DocAccounting/views/ui/ui_docs_upload_dialog.py
pyuic5 -x DocAccounting/views/ui/DocsAccReadDialog.ui -o DocAccounting/views/ui/ui_docs_acc_read_dialog.py
pyuic5 -x DocAccounting/views/ui/DatabaseToolsDialog.ui -o DocAccounting/views/ui/ui_docs_database_tools_dialog.py
pyuic5 -x DocAccounting/views/ui/PositionsEditDialog.ui -o DocAccounting/views/ui/ui_positions_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/DevelopersEditDialog.ui -o DocAccounting/views/ui/ui_developers_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/StatusDocsEditDialog.ui -o DocAccounting/views/ui/ui_statusdocs_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/CategoryDocsEditDialog.ui -o DocAccounting/views/ui/ui_category_docs_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/DocsRegulationDialog.ui -o DocAccounting/views/ui/ui_docs_regulation_dialog.py
pyuic5 -x DocAccounting/views/ui/DocsRegulationEditDialog.ui -o DocAccounting/views/ui/ui_docs_regulation_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/SourcesEditDialog.ui -o DocAccounting/views/ui/ui_sources_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/EmployeesEditDialog.ui -o DocAccounting/views/ui/ui_employees_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/WindowStylesDialog.ui -o DocAccounting/views/ui/ui_window_styles_dialog.py
pyuic5 -x DocAccounting/views/ui/DepartmentsDialog.ui -o DocAccounting/views/ui/ui_departments_dialog.py
pyuic5 -x DocAccounting/views/ui/DepartmentsEditDialog.ui -o DocAccounting/views/ui/ui_departments_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/ViewDocsDialog.ui -o DocAccounting/views/ui/ui_view_docs_dialog.py
pyuic5 -x DocAccounting/views/ui/ViewDocsEditDialog.ui -o DocAccounting/views/ui/ui_view_docs_edit_dialog.py
pyuic5 -x DocAccounting/views/ui/DocsChangeDialog.ui -o DocAccounting/views/ui/ui_docs_change_dialog.py
pyrcc5 res.qrc -o res_rc.py