# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DocAccounting/views/ui/CategoryDocsEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CategoryDocsEditDialog(object):
    def setupUi(self, CategoryDocsEditDialog):
        CategoryDocsEditDialog.setObjectName("CategoryDocsEditDialog")
        CategoryDocsEditDialog.resize(658, 348)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        CategoryDocsEditDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CategoryDocsEditDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(CategoryDocsEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.titleEdit = QtWidgets.QLineEdit(CategoryDocsEditDialog)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(CategoryDocsEditDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(CategoryDocsEditDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(CategoryDocsEditDialog)
        self.cancelButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(CategoryDocsEditDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.codeEdit = QtWidgets.QLineEdit(CategoryDocsEditDialog)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 0, 1, 1, 1)
        self.okButton = QtWidgets.QPushButton(CategoryDocsEditDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 2, 2, 1, 1)

        self.retranslateUi(CategoryDocsEditDialog)
        QtCore.QMetaObject.connectSlotsByName(CategoryDocsEditDialog)

    def retranslateUi(self, CategoryDocsEditDialog):
        _translate = QtCore.QCoreApplication.translate
        CategoryDocsEditDialog.setWindowTitle(_translate("CategoryDocsEditDialog", "Категории документов"))
        self.label_2.setText(_translate("CategoryDocsEditDialog", "Код"))
        self.label_3.setText(_translate("CategoryDocsEditDialog", "Наименование"))
        self.cancelButton.setText(_translate("CategoryDocsEditDialog", "Отмена"))
        self.okButton.setText(_translate("CategoryDocsEditDialog", "OK"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CategoryDocsEditDialog = QtWidgets.QWidget()
    ui = Ui_CategoryDocsEditDialog()
    ui.setupUi(CategoryDocsEditDialog)
    CategoryDocsEditDialog.show()
    sys.exit(app.exec_())
