# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DocAccounting/views/ui/DocsRegulationEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DocsRegulationEditDialog(object):
    def setupUi(self, DocsRegulationEditDialog):
        DocsRegulationEditDialog.setObjectName("DocsRegulationEditDialog")
        DocsRegulationEditDialog.resize(658, 458)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        DocsRegulationEditDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DocsRegulationEditDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(DocsRegulationEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(DocsRegulationEditDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.titleEdit = QtWidgets.QLineEdit(DocsRegulationEditDialog)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 2, 1, 1, 1)
        self.codeEdit = QtWidgets.QLineEdit(DocsRegulationEditDialog)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 0, 1, 1, 1)
        self.urlEdit = QtWidgets.QLineEdit(DocsRegulationEditDialog)
        self.urlEdit.setObjectName("urlEdit")
        self.gridLayout.addWidget(self.urlEdit, 5, 1, 1, 1)
        self.pathEdit = QtWidgets.QLineEdit(DocsRegulationEditDialog)
        self.pathEdit.setObjectName("pathEdit")
        self.gridLayout.addWidget(self.pathEdit, 3, 1, 1, 1)
        self.docs_extEdit = QtWidgets.QLineEdit(DocsRegulationEditDialog)
        self.docs_extEdit.setObjectName("docs_extEdit")
        self.gridLayout.addWidget(self.docs_extEdit, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(DocsRegulationEditDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(DocsRegulationEditDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(DocsRegulationEditDialog)
        self.cancelButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 6, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(DocsRegulationEditDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(DocsRegulationEditDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(DocsRegulationEditDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(DocsRegulationEditDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.categoryEdit = QtWidgets.QLineEdit(DocsRegulationEditDialog)
        self.categoryEdit.setObjectName("categoryEdit")
        self.gridLayout.addWidget(self.categoryEdit, 1, 1, 1, 1)
        self.okButton = QtWidgets.QPushButton(DocsRegulationEditDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 6, 2, 1, 1)
        self.pathButton = QtWidgets.QPushButton(DocsRegulationEditDialog)
        self.pathButton.setObjectName("pathButton")
        self.gridLayout.addWidget(self.pathButton, 3, 2, 1, 1)

        self.retranslateUi(DocsRegulationEditDialog)
        QtCore.QMetaObject.connectSlotsByName(DocsRegulationEditDialog)

    def retranslateUi(self, DocsRegulationEditDialog):
        _translate = QtCore.QCoreApplication.translate
        DocsRegulationEditDialog.setWindowTitle(_translate("DocsRegulationEditDialog", "Нормативные документы"))
        self.label_2.setText(_translate("DocsRegulationEditDialog", "Код"))
        self.label_4.setText(_translate("DocsRegulationEditDialog", "Наименование"))
        self.cancelButton.setText(_translate("DocsRegulationEditDialog", "Отмена"))
        self.label_7.setText(_translate("DocsRegulationEditDialog", "URL"))
        self.label_3.setText(_translate("DocsRegulationEditDialog", "Категория"))
        self.label_5.setText(_translate("DocsRegulationEditDialog", "Путь к документу"))
        self.label_6.setText(_translate("DocsRegulationEditDialog", "Расширение документа"))
        self.okButton.setText(_translate("DocsRegulationEditDialog", "OK"))
        self.pathButton.setText(_translate("DocsRegulationEditDialog", "..."))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DocsRegulationEditDialog = QtWidgets.QWidget()
    ui = Ui_DocsRegulationEditDialog()
    ui.setupUi(DocsRegulationEditDialog)
    DocsRegulationEditDialog.show()
    sys.exit(app.exec_())
