# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DocAccounting/views/ui/DevelopersEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DevelopersEditDialog(object):
    def setupUi(self, DevelopersEditDialog):
        DevelopersEditDialog.setObjectName("DevelopersEditDialog")
        DevelopersEditDialog.resize(658, 348)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        DevelopersEditDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DevelopersEditDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(DevelopersEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(DevelopersEditDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.okButton = QtWidgets.QPushButton(DevelopersEditDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(DevelopersEditDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(DevelopersEditDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.titleEdit = QtWidgets.QLineEdit(DevelopersEditDialog)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 1, 1, 1, 1)
        self.codeEdit = QtWidgets.QLineEdit(DevelopersEditDialog)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 0, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(DevelopersEditDialog)
        self.cancelButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 3, 3, 1, 1)
        self.commentsEdit = QtWidgets.QLineEdit(DevelopersEditDialog)
        self.commentsEdit.setObjectName("commentsEdit")
        self.gridLayout.addWidget(self.commentsEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(DevelopersEditDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)

        self.retranslateUi(DevelopersEditDialog)
        QtCore.QMetaObject.connectSlotsByName(DevelopersEditDialog)

    def retranslateUi(self, DevelopersEditDialog):
        _translate = QtCore.QCoreApplication.translate
        DevelopersEditDialog.setWindowTitle(_translate("DevelopersEditDialog", "Разработчики"))
        self.label_2.setText(_translate("DevelopersEditDialog", "Код"))
        self.okButton.setText(_translate("DevelopersEditDialog", "OK"))
        self.label_3.setText(_translate("DevelopersEditDialog", "Наименование"))
        self.cancelButton.setText(_translate("DevelopersEditDialog", "Отмена"))
        self.label_4.setText(_translate("DevelopersEditDialog", "Комментарий"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DevelopersEditDialog = QtWidgets.QWidget()
    ui = Ui_DevelopersEditDialog()
    ui.setupUi(DevelopersEditDialog)
    DevelopersEditDialog.show()
    sys.exit(app.exec_())
