# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DocAccounting/views/ui/SourcesEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SourcesEditDialog(object):
    def setupUi(self, SourcesEditDialog):
        SourcesEditDialog.setObjectName("SourcesEditDialog")
        SourcesEditDialog.resize(658, 348)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        SourcesEditDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SourcesEditDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(SourcesEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(SourcesEditDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(SourcesEditDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.titleEdit = QtWidgets.QLineEdit(SourcesEditDialog)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 1, 1, 1, 1)
        self.codeEdit = QtWidgets.QLineEdit(SourcesEditDialog)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(SourcesEditDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(SourcesEditDialog)
        self.cancelButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 3, 1, 1)
        self.okButton = QtWidgets.QPushButton(SourcesEditDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 2, 2, 1, 1)

        self.retranslateUi(SourcesEditDialog)
        QtCore.QMetaObject.connectSlotsByName(SourcesEditDialog)

    def retranslateUi(self, SourcesEditDialog):
        _translate = QtCore.QCoreApplication.translate
        SourcesEditDialog.setWindowTitle(_translate("SourcesEditDialog", "Источники"))
        self.label_2.setText(_translate("SourcesEditDialog", "Код"))
        self.label_3.setText(_translate("SourcesEditDialog", "Наименование"))
        self.cancelButton.setText(_translate("SourcesEditDialog", "Отмена"))
        self.okButton.setText(_translate("SourcesEditDialog", "OK"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SourcesEditDialog = QtWidgets.QWidget()
    ui = Ui_SourcesEditDialog()
    ui.setupUi(SourcesEditDialog)
    SourcesEditDialog.show()
    sys.exit(app.exec_())
