# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DocAccounting/views/ui/StatusDocsEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatusDocsEditDialog(object):
    def setupUi(self, StatusDocsEditDialog):
        StatusDocsEditDialog.setObjectName("StatusDocsEditDialog")
        StatusDocsEditDialog.resize(658, 348)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        StatusDocsEditDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StatusDocsEditDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(StatusDocsEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.cancelButton = QtWidgets.QPushButton(StatusDocsEditDialog)
        self.cancelButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 3, 3, 1, 1)
        self.titleEdit = QtWidgets.QLineEdit(StatusDocsEditDialog)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(StatusDocsEditDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(StatusDocsEditDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.descriptionEdit = QtWidgets.QLineEdit(StatusDocsEditDialog)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridLayout.addWidget(self.descriptionEdit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(StatusDocsEditDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.codeEdit = QtWidgets.QLineEdit(StatusDocsEditDialog)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(StatusDocsEditDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.okButton = QtWidgets.QPushButton(StatusDocsEditDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 3, 2, 1, 1)

        self.retranslateUi(StatusDocsEditDialog)
        QtCore.QMetaObject.connectSlotsByName(StatusDocsEditDialog)

    def retranslateUi(self, StatusDocsEditDialog):
        _translate = QtCore.QCoreApplication.translate
        StatusDocsEditDialog.setWindowTitle(_translate("StatusDocsEditDialog", "Статус документа"))
        self.cancelButton.setText(_translate("StatusDocsEditDialog", "Отмена"))
        self.label_2.setText(_translate("StatusDocsEditDialog", "Код"))
        self.label_3.setText(_translate("StatusDocsEditDialog", "Наименование"))
        self.label_4.setText(_translate("StatusDocsEditDialog", "Описание"))
        self.okButton.setText(_translate("StatusDocsEditDialog", "OK"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StatusDocsEditDialog = QtWidgets.QWidget()
    ui = Ui_StatusDocsEditDialog()
    ui.setupUi(StatusDocsEditDialog)
    StatusDocsEditDialog.show()
    sys.exit(app.exec_())
