# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DocAccounting/views/ui/ViewDocsEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewDocsEditDialog(object):
    def setupUi(self, ViewDocsEditDialog):
        ViewDocsEditDialog.setObjectName("ViewDocsEditDialog")
        ViewDocsEditDialog.resize(658, 348)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        ViewDocsEditDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ViewDocsEditDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ViewDocsEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(ViewDocsEditDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.titleEdit = QtWidgets.QLineEdit(ViewDocsEditDialog)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(ViewDocsEditDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(ViewDocsEditDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.okButton = QtWidgets.QPushButton(ViewDocsEditDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 3, 2, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(ViewDocsEditDialog)
        self.cancelButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 3, 3, 1, 1)
        self.codeEdit = QtWidgets.QLineEdit(ViewDocsEditDialog)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(ViewDocsEditDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.descriptionEdit = QtWidgets.QLineEdit(ViewDocsEditDialog)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridLayout.addWidget(self.descriptionEdit, 2, 1, 1, 1)

        self.retranslateUi(ViewDocsEditDialog)
        QtCore.QMetaObject.connectSlotsByName(ViewDocsEditDialog)

    def retranslateUi(self, ViewDocsEditDialog):
        _translate = QtCore.QCoreApplication.translate
        ViewDocsEditDialog.setWindowTitle(_translate("ViewDocsEditDialog", "Вид документа"))
        self.label_2.setText(_translate("ViewDocsEditDialog", "Код"))
        self.label_3.setText(_translate("ViewDocsEditDialog", "Наименование"))
        self.okButton.setText(_translate("ViewDocsEditDialog", "OK"))
        self.cancelButton.setText(_translate("ViewDocsEditDialog", "Отмена"))
        self.label_4.setText(_translate("ViewDocsEditDialog", "Описание"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewDocsEditDialog = QtWidgets.QWidget()
    ui = Ui_ViewDocsEditDialog()
    ui.setupUi(ViewDocsEditDialog)
    ViewDocsEditDialog.show()
    sys.exit(app.exec_())
